/**
 * Generated by Supabase from the live schema — do not edit by hand.
 *
 * Regenerate after any migration with:
 *   npx supabase gen types typescript --project-id ubotsksjsqjhfrsqcrna > src/lib/supabase/database.types.ts
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.15";
  };
  public: {
    Tables: {
      employees: {
        Row: {
          active: boolean;
          created_at: string;
          hire_date: string | null;
          hourly_pay: number | null;
          id: string;
          login_code: string | null;
          name: string;
          password_set_at: string | null;
          performance_role: Database["public"]["Enums"]["performance_role"];
          setup_code: string | null;
          shift_group: Database["public"]["Enums"]["shift_group"];
          staff_password: string | null;
        };
        Insert: {
          active?: boolean;
          created_at?: string;
          hire_date?: string | null;
          hourly_pay?: number | null;
          id?: string;
          login_code?: string | null;
          name: string;
          password_set_at?: string | null;
          performance_role?: Database["public"]["Enums"]["performance_role"];
          setup_code?: string | null;
          shift_group?: Database["public"]["Enums"]["shift_group"];
          staff_password?: string | null;
        };
        Update: {
          active?: boolean;
          created_at?: string;
          hire_date?: string | null;
          hourly_pay?: number | null;
          id?: string;
          login_code?: string | null;
          name?: string;
          password_set_at?: string | null;
          performance_role?: Database["public"]["Enums"]["performance_role"];
          setup_code?: string | null;
          shift_group?: Database["public"]["Enums"]["shift_group"];
          staff_password?: string | null;
        };
        Relationships: [];
      };
      employee_payroll_names: {
        Row: {
          created_at: string;
          employee_id: string;
          id: string;
          payroll_name: string;
        };
        Insert: {
          created_at?: string;
          employee_id: string;
          id?: string;
          payroll_name: string;
        };
        Update: {
          created_at?: string;
          employee_id?: string;
          id?: string;
          payroll_name?: string;
        };
        Relationships: [
          {
            foreignKeyName: "employee_payroll_names_employee_id_fkey";
            columns: ["employee_id"];
            isOneToOne: false;
            referencedRelation: "employees";
            referencedColumns: ["id"];
          },
        ];
      };
      pay_stub_batches: {
        Row: {
          created_at: string;
          id: string;
          page_count: number;
          pay_date: string | null;
          period_end: string | null;
          period_start: string | null;
          released_at: string | null;
          source_filename: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          page_count: number;
          pay_date?: string | null;
          period_end?: string | null;
          period_start?: string | null;
          released_at?: string | null;
          source_filename: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          page_count?: number;
          pay_date?: string | null;
          period_end?: string | null;
          period_start?: string | null;
          released_at?: string | null;
          source_filename?: string;
        };
        Relationships: [];
      };
      pay_stubs: {
        Row: {
          batch_id: string;
          created_at: string;
          employee_id: string | null;
          id: string;
          match_source: string;
          page_number: number;
          payroll_name: string | null;
          skipped: boolean;
          storage_path: string;
        };
        Insert: {
          batch_id: string;
          created_at?: string;
          employee_id?: string | null;
          id?: string;
          match_source?: string;
          page_number: number;
          payroll_name?: string | null;
          skipped?: boolean;
          storage_path: string;
        };
        Update: {
          batch_id?: string;
          created_at?: string;
          employee_id?: string | null;
          id?: string;
          match_source?: string;
          page_number?: number;
          payroll_name?: string | null;
          skipped?: boolean;
          storage_path?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pay_stubs_batch_id_fkey";
            columns: ["batch_id"];
            isOneToOne: false;
            referencedRelation: "pay_stub_batches";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "pay_stubs_employee_id_fkey";
            columns: ["employee_id"];
            isOneToOne: false;
            referencedRelation: "employees";
            referencedColumns: ["id"];
          },
        ];
      };
      interviews: {
        Row: {
          application_id: string | null;
          created_at: string;
          id: string;
          interview_date: string;
          interview_time: string;
          name: string;
          note: string;
          phone: string;
        };
        Insert: {
          application_id?: string | null;
          created_at?: string;
          id?: string;
          interview_date: string;
          interview_time?: string;
          name: string;
          note?: string;
          phone?: string;
        };
        Update: {
          application_id?: string | null;
          created_at?: string;
          id?: string;
          interview_date?: string;
          interview_time?: string;
          name?: string;
          note?: string;
          phone?: string;
        };
        Relationships: [
          {
            foreignKeyName: "interviews_application_id_fkey";
            columns: ["application_id"];
            isOneToOne: false;
            referencedRelation: "job_applications";
            referencedColumns: ["id"];
          },
        ];
      };
      job_applications: {
        Row: {
          age: string;
          availability: string;
          email: string;
          employment_type: string;
          experience: string;
          first_name: string;
          food_service: string;
          id: string;
          last_name: string;
          location: string;
          note: string;
          phone: string;
          position: string;
          status: Database["public"]["Enums"]["application_status"];
          submitted_at: string;
          transportation: string;
          work_authorized: string;
        };
        Insert: {
          age?: string;
          availability?: string;
          email?: string;
          employment_type?: string;
          experience?: string;
          first_name?: string;
          food_service?: string;
          id?: string;
          last_name?: string;
          location?: string;
          note?: string;
          phone?: string;
          position?: string;
          status?: Database["public"]["Enums"]["application_status"];
          submitted_at?: string;
          transportation?: string;
          work_authorized?: string;
        };
        Update: {
          age?: string;
          availability?: string;
          email?: string;
          employment_type?: string;
          experience?: string;
          first_name?: string;
          food_service?: string;
          id?: string;
          last_name?: string;
          location?: string;
          note?: string;
          phone?: string;
          position?: string;
          status?: Database["public"]["Enums"]["application_status"];
          submitted_at?: string;
          transportation?: string;
          work_authorized?: string;
        };
        Relationships: [];
      };
      published_shifts: {
        Row: {
          employee_id: string;
          hour: number | null;
          row_index: number;
          shift_date: string;
          start_minute: number;
          week_start: string;
        };
        Insert: {
          employee_id: string;
          row_index: number;
          shift_date: string;
          start_minute: number;
          week_start: string;
        };
        Update: {
          employee_id?: string;
          row_index?: number;
          shift_date?: string;
          start_minute?: number;
          week_start?: string;
        };
        Relationships: [
          {
            foreignKeyName: "published_shifts_employee_id_fkey";
            columns: ["employee_id"];
            isOneToOne: false;
            referencedRelation: "employees";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "published_shifts_week_start_fkey";
            columns: ["week_start"];
            isOneToOne: false;
            referencedRelation: "published_weeks";
            referencedColumns: ["week_start"];
          },
        ];
      };
      published_weeks: {
        Row: {
          published_at: string;
          week_start: string;
        };
        Insert: {
          published_at?: string;
          week_start: string;
        };
        Update: {
          published_at?: string;
          week_start?: string;
        };
        Relationships: [];
      };
      published_tip_rates: {
        Row: {
          per_hour: number;
          period_end: string;
          period_start: string;
          published_at: string;
        };
        Insert: {
          per_hour: number;
          period_end: string;
          period_start: string;
          published_at?: string;
        };
        Update: {
          per_hour?: number;
          period_end?: string;
          period_start?: string;
          published_at?: string;
        };
        Relationships: [];
      };
      staff_login_attempts: {
        Row: {
          attempted_at: string;
          id: number;
          ip: string;
          succeeded: boolean;
        };
        Insert: {
          attempted_at?: string;
          id?: never;
          ip: string;
          succeeded: boolean;
        };
        Update: {
          attempted_at?: string;
          id?: never;
          ip?: string;
          succeeded?: boolean;
        };
        Relationships: [];
      };
      recurring_time_off: {
        Row: {
          created_at: string;
          day: Database["public"]["Enums"]["day_key"];
          employee_id: string;
          id: string;
          reason: string;
        };
        Insert: {
          created_at?: string;
          day: Database["public"]["Enums"]["day_key"];
          employee_id: string;
          id?: string;
          reason?: string;
        };
        Update: {
          created_at?: string;
          day?: Database["public"]["Enums"]["day_key"];
          employee_id?: string;
          id?: string;
          reason?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recurring_time_off_employee_id_fkey";
            columns: ["employee_id"];
            isOneToOne: false;
            referencedRelation: "employees";
            referencedColumns: ["id"];
          },
        ];
      };
      schedule_settings: {
        Row: {
          id: boolean;
          row_count: number;
          updated_at: string;
        };
        Insert: {
          id?: boolean;
          row_count?: number;
          updated_at?: string;
        };
        Update: {
          id?: boolean;
          row_count?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      shift_assignments: {
        Row: {
          created_at: string;
          employee_id: string;
          hour: number | null;
          row_index: number;
          shift_date: string;
          start_minute: number;
        };
        Insert: {
          created_at?: string;
          employee_id: string;
          row_index: number;
          shift_date: string;
          start_minute: number;
        };
        Update: {
          created_at?: string;
          employee_id?: string;
          row_index?: number;
          shift_date?: string;
          start_minute?: number;
        };
        Relationships: [
          {
            foreignKeyName: "shift_assignments_employee_id_fkey";
            columns: ["employee_id"];
            isOneToOne: false;
            referencedRelation: "employees";
            referencedColumns: ["id"];
          },
        ];
      };
      text_snippets: {
        Row: {
          body: string;
          created_at: string;
          id: string;
          sort_order: number;
          title: string;
          updated_at: string;
        };
        Insert: {
          body?: string;
          created_at?: string;
          id?: string;
          sort_order?: number;
          title?: string;
          updated_at?: string;
        };
        Update: {
          body?: string;
          created_at?: string;
          id?: string;
          sort_order?: number;
          title?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      time_off_requests: {
        Row: {
          created_at: string;
          deleted_at: string | null;
          employee_id: string;
          end_date: string;
          id: string;
          reason: string;
          requested_at: string;
          start_date: string;
          status: Database["public"]["Enums"]["time_off_status"];
        };
        Insert: {
          created_at?: string;
          deleted_at?: string | null;
          employee_id: string;
          end_date: string;
          id?: string;
          reason?: string;
          requested_at?: string;
          start_date: string;
          status?: Database["public"]["Enums"]["time_off_status"];
        };
        Update: {
          created_at?: string;
          deleted_at?: string | null;
          employee_id?: string;
          end_date?: string;
          id?: string;
          reason?: string;
          requested_at?: string;
          start_date?: string;
          status?: Database["public"]["Enums"]["time_off_status"];
        };
        Relationships: [
          {
            foreignKeyName: "time_off_requests_employee_id_fkey";
            columns: ["employee_id"];
            isOneToOne: false;
            referencedRelation: "employees";
            referencedColumns: ["id"];
          },
        ];
      };
      truck_items: {
        Row: {
          brand: string;
          category: string;
          created_at: string;
          id: string;
          name: string;
          pack_size: string;
          par_quantity: number;
          sort_order: number;
          supplier: string;
          supplier_item_code: string;
          unit: string;
          unit_price: number | null;
        };
        Insert: {
          brand?: string;
          category?: string;
          created_at?: string;
          id?: string;
          name: string;
          pack_size?: string;
          par_quantity?: number;
          sort_order?: number;
          supplier?: string;
          supplier_item_code?: string;
          unit?: string;
          unit_price?: number | null;
        };
        Update: {
          brand?: string;
          category?: string;
          created_at?: string;
          id?: string;
          name?: string;
          pack_size?: string;
          par_quantity?: number;
          sort_order?: number;
          supplier?: string;
          supplier_item_code?: string;
          unit?: string;
          unit_price?: number | null;
        };
        Relationships: [];
      };
      truck_order_lines: {
        Row: {
          category: string;
          created_at: string;
          id: string;
          item_id: string | null;
          name: string;
          order_id: string;
          pack_size: string;
          quantity: number;
          sort_order: number;
          supplier_item_code: string;
          unit: string;
          unit_price: number | null;
        };
        Insert: {
          category?: string;
          created_at?: string;
          id?: string;
          item_id?: string | null;
          name: string;
          order_id: string;
          pack_size?: string;
          quantity?: number;
          sort_order?: number;
          supplier_item_code?: string;
          unit?: string;
          unit_price?: number | null;
        };
        Update: {
          category?: string;
          created_at?: string;
          id?: string;
          item_id?: string | null;
          name?: string;
          order_id?: string;
          pack_size?: string;
          quantity?: number;
          sort_order?: number;
          supplier_item_code?: string;
          unit?: string;
          unit_price?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "truck_order_lines_item_id_fkey";
            columns: ["item_id"];
            isOneToOne: false;
            referencedRelation: "truck_items";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "truck_order_lines_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "truck_orders";
            referencedColumns: ["id"];
          },
        ];
      };
      truck_orders: {
        Row: {
          created_at: string;
          delivery_date: string | null;
          id: string;
          invoice_number: string;
          invoice_total: number | null;
          note: string;
          order_date: string;
          received_at: string | null;
          status: Database["public"]["Enums"]["truck_order_status"];
          submitted_at: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          delivery_date?: string | null;
          id?: string;
          invoice_number?: string;
          invoice_total?: number | null;
          note?: string;
          order_date: string;
          received_at?: string | null;
          status?: Database["public"]["Enums"]["truck_order_status"];
          submitted_at?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          delivery_date?: string | null;
          id?: string;
          invoice_number?: string;
          invoice_total?: number | null;
          note?: string;
          order_date?: string;
          received_at?: string | null;
          status?: Database["public"]["Enums"]["truck_order_status"];
          submitted_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      employee_stations: {
        Row: {
          employee_id: string;
          station_id: string;
        };
        Insert: {
          employee_id: string;
          station_id: string;
        };
        Update: {
          employee_id?: string;
          station_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "employee_stations_employee_id_fkey";
            columns: ["employee_id"];
            isOneToOne: false;
            referencedRelation: "employees";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "employee_stations_station_id_fkey";
            columns: ["station_id"];
            isOneToOne: false;
            referencedRelation: "performance_stations";
            referencedColumns: ["id"];
          },
        ];
      };
      performance_metric_roles: {
        Row: {
          metric_id: string;
          role: Database["public"]["Enums"]["performance_role"];
        };
        Insert: {
          metric_id: string;
          role: Database["public"]["Enums"]["performance_role"];
        };
        Update: {
          metric_id?: string;
          role?: Database["public"]["Enums"]["performance_role"];
        };
        Relationships: [
          {
            foreignKeyName: "performance_metric_roles_metric_id_fkey";
            columns: ["metric_id"];
            isOneToOne: false;
            referencedRelation: "performance_metrics";
            referencedColumns: ["id"];
          },
        ];
      };
      performance_metric_stations: {
        Row: {
          metric_id: string;
          station_id: string;
        };
        Insert: {
          metric_id: string;
          station_id: string;
        };
        Update: {
          metric_id?: string;
          station_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "performance_metric_stations_metric_id_fkey";
            columns: ["metric_id"];
            isOneToOne: false;
            referencedRelation: "performance_metrics";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "performance_metric_stations_station_id_fkey";
            columns: ["station_id"];
            isOneToOne: false;
            referencedRelation: "performance_stations";
            referencedColumns: ["id"];
          },
        ];
      };
      performance_metrics: {
        Row: {
          amber_at: number | null;
          archived: boolean;
          category: string;
          created_at: string;
          description: string;
          direction: Database["public"]["Enums"]["metric_direction"];
          frequency: Database["public"]["Enums"]["metric_frequency"];
          green_at: number | null;
          id: string;
          lagging: boolean;
          name: string;
          scope: Database["public"]["Enums"]["metric_scope"];
          sort_order: number;
          target: number | null;
          target_max: number | null;
          target_min: number | null;
          type: Database["public"]["Enums"]["metric_type"];
          unit: string;
          weight: number;
        };
        Insert: {
          amber_at?: number | null;
          archived?: boolean;
          category?: string;
          created_at?: string;
          description?: string;
          direction?: Database["public"]["Enums"]["metric_direction"];
          frequency?: Database["public"]["Enums"]["metric_frequency"];
          green_at?: number | null;
          id?: string;
          lagging?: boolean;
          name: string;
          scope?: Database["public"]["Enums"]["metric_scope"];
          sort_order?: number;
          target?: number | null;
          target_max?: number | null;
          target_min?: number | null;
          type?: Database["public"]["Enums"]["metric_type"];
          unit?: string;
          weight?: number;
        };
        Update: {
          amber_at?: number | null;
          archived?: boolean;
          category?: string;
          created_at?: string;
          description?: string;
          direction?: Database["public"]["Enums"]["metric_direction"];
          frequency?: Database["public"]["Enums"]["metric_frequency"];
          green_at?: number | null;
          id?: string;
          lagging?: boolean;
          name?: string;
          scope?: Database["public"]["Enums"]["metric_scope"];
          sort_order?: number;
          target?: number | null;
          target_max?: number | null;
          target_min?: number | null;
          type?: Database["public"]["Enums"]["metric_type"];
          unit?: string;
          weight?: number;
        };
        Relationships: [];
      };
      performance_stations: {
        Row: {
          created_at: string;
          id: string;
          name: string;
          sort_order: number;
        };
        Insert: {
          created_at?: string;
          id?: string;
          name: string;
          sort_order?: number;
        };
        Update: {
          created_at?: string;
          id?: string;
          name?: string;
          sort_order?: number;
        };
        Relationships: [];
      };
      item_components: {
        Row: {
          basis: Database["public"]["Enums"]["unit_basis"];
          component_id: string;
          id: string;
          note: string;
          parent_id: string;
          quantity: number;
          sort_order: number;
        };
        Insert: {
          basis?: Database["public"]["Enums"]["unit_basis"];
          component_id: string;
          id?: string;
          note?: string;
          parent_id: string;
          quantity: number;
          sort_order?: number;
        };
        Update: {
          basis?: Database["public"]["Enums"]["unit_basis"];
          component_id?: string;
          id?: string;
          note?: string;
          parent_id?: string;
          quantity?: number;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "item_components_component_id_fkey";
            columns: ["component_id"];
            isOneToOne: false;
            referencedRelation: "items";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "item_components_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "items";
            referencedColumns: ["id"];
          },
        ];
      };
      item_locations: {
        Row: {
          id: string;
          item_id: string;
          location_id: string;
        };
        Insert: {
          id?: string;
          item_id: string;
          location_id: string;
        };
        Update: {
          id?: string;
          item_id?: string;
          location_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "item_locations_item_id_fkey";
            columns: ["item_id"];
            isOneToOne: false;
            referencedRelation: "items";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "item_locations_location_id_fkey";
            columns: ["location_id"];
            isOneToOne: false;
            referencedRelation: "locations";
            referencedColumns: ["id"];
          },
        ];
      };
      item_revisions: {
        Row: {
          changed_at: string;
          changed_by: string;
          id: string;
          item_id: string;
          snapshot: Json;
          summary: string;
          version: number;
        };
        Insert: {
          changed_at?: string;
          changed_by?: string;
          id?: string;
          item_id: string;
          snapshot: Json;
          summary?: string;
          version: number;
        };
        Update: {
          changed_at?: string;
          changed_by?: string;
          id?: string;
          item_id?: string;
          snapshot?: Json;
          summary?: string;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "item_revisions_item_id_fkey";
            columns: ["item_id"];
            isOneToOne: false;
            referencedRelation: "items";
            referencedColumns: ["id"];
          },
        ];
      };
      item_suppliers: {
        Row: {
          approved: boolean;
          cost: number | null;
          created_at: string;
          id: string;
          is_primary: boolean;
          item_id: string;
          pack_size: string;
          purchase_unit: string;
          supplier_id: string;
          supplier_part_number: string;
        };
        Insert: {
          approved?: boolean;
          cost?: number | null;
          created_at?: string;
          id?: string;
          is_primary?: boolean;
          item_id: string;
          pack_size?: string;
          purchase_unit?: string;
          supplier_id: string;
          supplier_part_number?: string;
        };
        Update: {
          approved?: boolean;
          cost?: number | null;
          created_at?: string;
          id?: string;
          is_primary?: boolean;
          item_id?: string;
          pack_size?: string;
          purchase_unit?: string;
          supplier_id?: string;
          supplier_part_number?: string;
        };
        Relationships: [
          {
            foreignKeyName: "item_suppliers_item_id_fkey";
            columns: ["item_id"];
            isOneToOne: false;
            referencedRelation: "items";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "item_suppliers_supplier_id_fkey";
            columns: ["supplier_id"];
            isOneToOne: false;
            referencedRelation: "suppliers";
            referencedColumns: ["id"];
          },
        ];
      };
      items: {
        Row: {
          aliases: string[];
          allergens: string[];
          available_everywhere: boolean;
          batch_yield_quantity: number;
          category: string;
          code: string;
          created_at: string;
          customer_name: string;
          date_label_rule: string;
          id: string;
          internal_name: string;
          menu_price: number | null;
          notes: string;
          nutrition: Json;
          pack_size: string;
          par_level: number | null;
          photo_url: string;
          portion_unit: string;
          portions_per_stock_unit: number | null;
          purchase_cost: number | null;
          purchase_unit: string;
          recipe_url: string;
          reorder_point: number | null;
          scope: Database["public"]["Enums"]["item_scope"];
          shelf_life_days: number | null;
          sop_links: Json;
          status: Database["public"]["Enums"]["item_status"];
          stock_per_purchase_unit: number | null;
          stock_unit: string;
          storage_temp: string;
          storage_zone: Database["public"]["Enums"]["storage_zone"];
          subcategory: string;
          type: Database["public"]["Enums"]["item_type"];
          updated_at: string;
          updated_by: string;
          version: number;
          yield_factor: number;
        };
        Insert: {
          aliases?: string[];
          allergens?: string[];
          available_everywhere?: boolean;
          batch_yield_quantity?: number;
          category?: string;
          code: string;
          created_at?: string;
          customer_name?: string;
          date_label_rule?: string;
          id?: string;
          internal_name: string;
          menu_price?: number | null;
          notes?: string;
          nutrition?: Json;
          pack_size?: string;
          par_level?: number | null;
          photo_url?: string;
          portion_unit?: string;
          portions_per_stock_unit?: number | null;
          purchase_cost?: number | null;
          purchase_unit?: string;
          recipe_url?: string;
          reorder_point?: number | null;
          scope?: Database["public"]["Enums"]["item_scope"];
          shelf_life_days?: number | null;
          sop_links?: Json;
          status?: Database["public"]["Enums"]["item_status"];
          stock_per_purchase_unit?: number | null;
          stock_unit?: string;
          storage_temp?: string;
          storage_zone?: Database["public"]["Enums"]["storage_zone"];
          subcategory?: string;
          type: Database["public"]["Enums"]["item_type"];
          updated_at?: string;
          updated_by?: string;
          version?: number;
          yield_factor?: number;
        };
        Update: {
          aliases?: string[];
          allergens?: string[];
          available_everywhere?: boolean;
          batch_yield_quantity?: number;
          category?: string;
          code?: string;
          created_at?: string;
          customer_name?: string;
          date_label_rule?: string;
          id?: string;
          internal_name?: string;
          menu_price?: number | null;
          notes?: string;
          nutrition?: Json;
          pack_size?: string;
          par_level?: number | null;
          photo_url?: string;
          portion_unit?: string;
          portions_per_stock_unit?: number | null;
          purchase_cost?: number | null;
          purchase_unit?: string;
          recipe_url?: string;
          reorder_point?: number | null;
          scope?: Database["public"]["Enums"]["item_scope"];
          shelf_life_days?: number | null;
          sop_links?: Json;
          status?: Database["public"]["Enums"]["item_status"];
          stock_per_purchase_unit?: number | null;
          stock_unit?: string;
          storage_temp?: string;
          storage_zone?: Database["public"]["Enums"]["storage_zone"];
          subcategory?: string;
          type?: Database["public"]["Enums"]["item_type"];
          updated_at?: string;
          updated_by?: string;
          version?: number;
          yield_factor?: number;
        };
        Relationships: [];
      };
      locations: {
        Row: {
          active: boolean;
          code: string;
          created_at: string;
          id: string;
          name: string;
          region: string;
        };
        Insert: {
          active?: boolean;
          code: string;
          created_at?: string;
          id?: string;
          name: string;
          region?: string;
        };
        Update: {
          active?: boolean;
          code?: string;
          created_at?: string;
          id?: string;
          name?: string;
          region?: string;
        };
        Relationships: [];
      };
      suppliers: {
        Row: {
          account_number: string;
          active: boolean;
          contact: string;
          created_at: string;
          id: string;
          name: string;
          notes: string;
        };
        Insert: {
          account_number?: string;
          active?: boolean;
          contact?: string;
          created_at?: string;
          id?: string;
          name: string;
          notes?: string;
        };
        Update: {
          account_number?: string;
          active?: boolean;
          contact?: string;
          created_at?: string;
          id?: string;
          name?: string;
          notes?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      application_status: "new" | "contacted" | "interview" | "hired" | "passed";
      day_key:
        | "monday"
        | "tuesday"
        | "wednesday"
        | "thursday"
        | "friday"
        | "saturday"
        | "sunday";
      item_scope: "core" | "optional" | "regional";
      item_status: "active" | "seasonal" | "regional" | "test" | "discontinued";
      item_type:
        | "raw"
        | "prepped"
        | "menu"
        | "modifier"
        | "packaging"
        | "chemical"
        | "smallware"
        | "marketing";
      metric_direction: "higher" | "lower" | "range" | "exact";
      metric_frequency: "shift" | "daily" | "weekly" | "monthly";
      metric_scope: "individual" | "station" | "leadership";
      metric_type:
        | "number"
        | "percentage"
        | "currency"
        | "count"
        | "duration"
        | "pass_fail"
        | "rating";
      performance_role: "crew" | "shift_lead" | "manager";
      shift_group: "morning" | "night" | "other";
      storage_zone: "none" | "dry" | "refrigerated" | "frozen";
      time_off_status: "pending" | "approved" | "denied";
      truck_order_status: "draft" | "submitted" | "received";
      unit_basis: "stock" | "portion";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
