/**
 * Generated by Supabase from the live schema — do not edit by hand.
 *
 * Regenerate after any migration with:
 *   npx supabase gen types typescript --project-id ubotsksjsqjhfrsqcrna > src/lib/supabase/database.types.ts
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.15";
  };
  public: {
    Tables: {
      employees: {
        Row: {
          created_at: string;
          id: string;
          login_code: string | null;
          name: string;
          shift_group: Database["public"]["Enums"]["shift_group"];
        };
        Insert: {
          created_at?: string;
          id?: string;
          login_code?: string | null;
          name: string;
          shift_group?: Database["public"]["Enums"]["shift_group"];
        };
        Update: {
          created_at?: string;
          id?: string;
          login_code?: string | null;
          name?: string;
          shift_group?: Database["public"]["Enums"]["shift_group"];
        };
        Relationships: [];
      };
      published_shifts: {
        Row: {
          employee_id: string;
          hour: number;
          row_index: number;
          shift_date: string;
          week_start: string;
        };
        Insert: {
          employee_id: string;
          hour: number;
          row_index: number;
          shift_date: string;
          week_start: string;
        };
        Update: {
          employee_id?: string;
          hour?: number;
          row_index?: number;
          shift_date?: string;
          week_start?: string;
        };
        Relationships: [
          {
            foreignKeyName: "published_shifts_employee_id_fkey";
            columns: ["employee_id"];
            isOneToOne: false;
            referencedRelation: "employees";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "published_shifts_week_start_fkey";
            columns: ["week_start"];
            isOneToOne: false;
            referencedRelation: "published_weeks";
            referencedColumns: ["week_start"];
          },
        ];
      };
      published_weeks: {
        Row: {
          published_at: string;
          week_start: string;
        };
        Insert: {
          published_at?: string;
          week_start: string;
        };
        Update: {
          published_at?: string;
          week_start?: string;
        };
        Relationships: [];
      };
      staff_login_attempts: {
        Row: {
          attempted_at: string;
          id: number;
          ip: string;
          succeeded: boolean;
        };
        Insert: {
          attempted_at?: string;
          id?: never;
          ip: string;
          succeeded: boolean;
        };
        Update: {
          attempted_at?: string;
          id?: never;
          ip?: string;
          succeeded?: boolean;
        };
        Relationships: [];
      };
      recurring_time_off: {
        Row: {
          created_at: string;
          day: Database["public"]["Enums"]["day_key"];
          employee_id: string;
          id: string;
          reason: string;
        };
        Insert: {
          created_at?: string;
          day: Database["public"]["Enums"]["day_key"];
          employee_id: string;
          id?: string;
          reason?: string;
        };
        Update: {
          created_at?: string;
          day?: Database["public"]["Enums"]["day_key"];
          employee_id?: string;
          id?: string;
          reason?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recurring_time_off_employee_id_fkey";
            columns: ["employee_id"];
            isOneToOne: false;
            referencedRelation: "employees";
            referencedColumns: ["id"];
          },
        ];
      };
      schedule_settings: {
        Row: {
          id: boolean;
          row_count: number;
          updated_at: string;
        };
        Insert: {
          id?: boolean;
          row_count?: number;
          updated_at?: string;
        };
        Update: {
          id?: boolean;
          row_count?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      shift_assignments: {
        Row: {
          created_at: string;
          employee_id: string;
          hour: number;
          row_index: number;
          shift_date: string;
        };
        Insert: {
          created_at?: string;
          employee_id: string;
          hour: number;
          row_index: number;
          shift_date: string;
        };
        Update: {
          created_at?: string;
          employee_id?: string;
          hour?: number;
          row_index?: number;
          shift_date?: string;
        };
        Relationships: [
          {
            foreignKeyName: "shift_assignments_employee_id_fkey";
            columns: ["employee_id"];
            isOneToOne: false;
            referencedRelation: "employees";
            referencedColumns: ["id"];
          },
        ];
      };
      time_off_requests: {
        Row: {
          created_at: string;
          employee_id: string;
          end_date: string;
          id: string;
          reason: string;
          requested_at: string;
          start_date: string;
          status: Database["public"]["Enums"]["time_off_status"];
        };
        Insert: {
          created_at?: string;
          employee_id: string;
          end_date: string;
          id?: string;
          reason?: string;
          requested_at?: string;
          start_date: string;
          status?: Database["public"]["Enums"]["time_off_status"];
        };
        Update: {
          created_at?: string;
          employee_id?: string;
          end_date?: string;
          id?: string;
          reason?: string;
          requested_at?: string;
          start_date?: string;
          status?: Database["public"]["Enums"]["time_off_status"];
        };
        Relationships: [
          {
            foreignKeyName: "time_off_requests_employee_id_fkey";
            columns: ["employee_id"];
            isOneToOne: false;
            referencedRelation: "employees";
            referencedColumns: ["id"];
          },
        ];
      };
      truck_items: {
        Row: {
          brand: string;
          category: string;
          created_at: string;
          id: string;
          name: string;
          pack_size: string;
          par_quantity: number;
          sort_order: number;
          supplier: string;
          supplier_item_code: string;
          unit: string;
          unit_price: number | null;
        };
        Insert: {
          brand?: string;
          category?: string;
          created_at?: string;
          id?: string;
          name: string;
          pack_size?: string;
          par_quantity?: number;
          sort_order?: number;
          supplier?: string;
          supplier_item_code?: string;
          unit?: string;
          unit_price?: number | null;
        };
        Update: {
          brand?: string;
          category?: string;
          created_at?: string;
          id?: string;
          name?: string;
          pack_size?: string;
          par_quantity?: number;
          sort_order?: number;
          supplier?: string;
          supplier_item_code?: string;
          unit?: string;
          unit_price?: number | null;
        };
        Relationships: [];
      };
      truck_order_lines: {
        Row: {
          category: string;
          created_at: string;
          id: string;
          item_id: string | null;
          name: string;
          order_id: string;
          pack_size: string;
          quantity: number;
          sort_order: number;
          supplier_item_code: string;
          unit: string;
          unit_price: number | null;
        };
        Insert: {
          category?: string;
          created_at?: string;
          id?: string;
          item_id?: string | null;
          name: string;
          order_id: string;
          pack_size?: string;
          quantity?: number;
          sort_order?: number;
          supplier_item_code?: string;
          unit?: string;
          unit_price?: number | null;
        };
        Update: {
          category?: string;
          created_at?: string;
          id?: string;
          item_id?: string | null;
          name?: string;
          order_id?: string;
          pack_size?: string;
          quantity?: number;
          sort_order?: number;
          supplier_item_code?: string;
          unit?: string;
          unit_price?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "truck_order_lines_item_id_fkey";
            columns: ["item_id"];
            isOneToOne: false;
            referencedRelation: "truck_items";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "truck_order_lines_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "truck_orders";
            referencedColumns: ["id"];
          },
        ];
      };
      truck_orders: {
        Row: {
          created_at: string;
          delivery_date: string | null;
          id: string;
          invoice_number: string;
          invoice_total: number | null;
          note: string;
          order_date: string;
          received_at: string | null;
          status: Database["public"]["Enums"]["truck_order_status"];
          submitted_at: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          delivery_date?: string | null;
          id?: string;
          invoice_number?: string;
          invoice_total?: number | null;
          note?: string;
          order_date: string;
          received_at?: string | null;
          status?: Database["public"]["Enums"]["truck_order_status"];
          submitted_at?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          delivery_date?: string | null;
          id?: string;
          invoice_number?: string;
          invoice_total?: number | null;
          note?: string;
          order_date?: string;
          received_at?: string | null;
          status?: Database["public"]["Enums"]["truck_order_status"];
          submitted_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      day_key:
        | "monday"
        | "tuesday"
        | "wednesday"
        | "thursday"
        | "friday"
        | "saturday"
        | "sunday";
      shift_group: "morning" | "night" | "other";
      time_off_status: "pending" | "approved" | "denied";
      truck_order_status: "draft" | "submitted" | "received";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
